### ISSUE TITLE
Please look to this backend if it is useful to your application or not !

### ISSUE THREAD

**Issue by Nokia808** [Unrud/djpdf#1]
Hi. I detect your application from my monitoring for Flathub on GitHub. Your application still not appearing in Flathub & for that I'm still not installing it & not test it yet.

However, I'm very interested in development of advanced PDF editor for Linux. Specially, I'm interested in PDF tools that able to manipulate & optimized scanned PDF files .....

Your application seem to be at heart of my interest ! For that I like to bring your attention to very strong backend I see it useful for your application. I'm not sure since I'm not programmer but externally it seem very useful to you. Please see it:

https://pypi.org/project/ocrmypdf/
https://github.com/jbarlow83/OCRmyPDF  

Look for it's options !

**Comment by Unrud** [comment]
> However, I'm very interested in development of advanced PDF editor for Linux.

It's out of scope of this project.
