### ISSUE TITLE
Are you intersted in creation advanced PDF editor ? Then look for QPDF !

### ISSUE THREAD

**Issue by Nokia808** [Unrud/djpdf#2]
Hi. if you are interested in creation an advanced PDF editor for Linux (which currently the only lack of Linux) then please look for this backend:

https://github.com/qpdf/qpdf
http://qpdf.sourceforge.net/
https://sourceforge.net/projects/qpdf/

Look for it's manual:
http://qpdf.sourceforge.net/files/qpdf-manual.html
http://qpdf.sourceforge.net/files/qpdf-manual.pdf

What it will be a GUI for this backend including ALL it's powers & functions ? It will be what Linux currently miss ....

It will be very helpful for peoples if you expand your application from just an OCR & optimizer for scanned PDF to full featured PDF editor.

**Comment by Unrud** [comment]
> What it will be a GUI for this backend including ALL it's powers & functions ? It will be what Linux currently miss ....

It's out of scope of this project.
