### ISSUE TITLE
Strange layout in magyar (Hungarian)

### ISSUE THREAD

**Issue by ovari** [Unrud/djpdf#20]
1. Buttons are different width
1. Text flow is strange

![image](https://github.com/Unrud/djpdf/assets/17465872/36eb11d4-1530-4533-bc09-008ffb8bbbc9)

Sorry, don't know how to get the version.

Thank you

**Comment by Unrud** [comment]
> Sorry, don't know how to get the version.

I never bothered to add an about dialog to the GUI. You can get the version from the command line interface: 

`
flatpak run --command=scans2pdf com.github.unrud.djpdf --version
`
