### ISSUE TITLE
Is jPDFTweak useful to you ?

### ISSUE THREAD

**Issue by Nokia808** [Unrud/djpdf#3]
Hi. Please look for this application (Java) if useful to you or not. It's developer stop from it's development. In fact it need some further new features to be a great application with complete PDF editing powers. It is jPDFTweak:

http://jpdftweak.sourceforge.net/
https://sourceforge.net/projects/jpdftweak/

It is a great crime not to have advanced PDF editor on Linux while we have such great backends like: QPDF & OCRmyPDF & such powerful Java GUI program like jPDFTweak ......

**Comment by Unrud** [comment]
> It is a great crime not to have advanced PDF editor on Linux while we have such great backends like:

It's out of scope of this project.
