### ISSUE TITLE
cli-only version

### ISSUE THREAD

**Issue by chrisersen** [Unrud/djpdf#5]
Because of limited resources it is not possible for me to install djpdf with the gui-dependencies. As far as I can see, djpdf without gui would be rather small. Would it be possible to make a cli-only version? (I don't know any other cli-tool to generate pdfs from scans with foreground-background-separation. And djvu isn't an option in my workflow.)

**Comment by Unrud** [comment]
Removing the GUI dependencies from the Flatpak version will only save ~50MB. Most disk space is used by the OCR models (~200 MB) and the KDE runtime (~960 MB).
Using the FreeDesktop runtime instead of the KDE only saves ~250 MB.

I think your best option is to install djpdf outside of Flatpak or Snap. Most dependencies should be available on most distributions.

**Dependencies**
  * [ImageMagick](http://www.imagemagick.org/)
  * [QPDF](https://github.com/qpdf/qpdf)

**Optional dependencies**
  * [jbig2enc](https://github.com/agl/jbig2enc) (required for JBIG2 support)
      * Probably not available on most distributions, but easy and fast to compile.
  * [Tesseract](https://github.com/tesseract-ocr/tesseract) (required for OCR support) and models for your desired languages

**Install**
```bash
env DJPDF_SETUP=no-gui pip3 install https://github.com/Unrud/djpdf/archive/master.zip
```

**Comment by chrisersen** [comment]
After installing it this way and running `scans2pdf ` I got an error message:
```shell
pip3 install webcolors colorama pdfrw psutil python-xmp-toolkit
pip3 install --no-deps https://github.com/Unrud/djpdf/archive/0.1.0.tar.gz
scans2pdf
 ```
resulted in:
> ```shell
> Traceback (most recent call last):
>   File "/home/ch/.local/bin/scans2pdf", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
>     @_call_aside
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'pyside2' distribution was not found and is required by djpdf
> ```

So additionally I installed pyside2 (I hoped I didn't have to) and also jbig2, libhocr0 and libhocr-dev after scans2pdf error messages. Running scans2pdf on a file now results in a error message I don't understand:

```shell
scans2pdf in.tif out.pdf
```
resulted in:

>```shell
> ERROR:Command '['convert', '-colorspace', 'sRGB', '-profile', '/home/ch/.local/lib/python3.6/site-packages/djpdf/argyllcms-srgb.icm', '-background', '#ffffff', '-alpha', 'remove', '-alpha', 'off', '/tmp/djpdf/bakip-002-2r.tif', '/tmp/djpdf-f6hirizu/image.png']' returned non-zero exit status 1
> ERROR:Operation failed
>```
convert from Imagemagick is installed.

**Comment by Unrud** [comment]
> So additionally I installed pyside2 (I hoped I didn't have to)

Sorry about that, I've added an option to the install without GUI:

```
env DJPDF_SETUP=no-gui pip3 install https://github.com/Unrud/djpdf/archive/master.zip
```

> Running scans2pdf on a file now results in a error message I don't understand:

Add ``--verbose`` to the command line. It will show the actual error messages from ImageMagick.

I did some testing on Ubuntu 18.04 and the distributed version of ImageMagick has some features disabled. The error messages look something like this:
```
DEBUG:convert-im6.q16: not authorized `…' @ error/constitute.c/WriteImage/1037.
```
In this case you have to compile ImageMagick yourself.

**Comment by chrisersen** [comment]
Is the problem you mention (`DEBUG:convert-im6.q16: not authorized`) not the same as in https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert ? Then it would just require to change `policy.xml` accordingly.

Thanks for the option without GUI. I just installed it and ran scans2pdf with `--verbose` getting:
```shell
DEBUG:Using selector: EpollSelector
DEBUG:Running command: ['convert', '-colorspace', 'sRGB', '-profile', '/home/ch/.local/lib/python3.6/site-packages/djpdf/argyllcms-srgb.icm', '-background', '#ffffff', '-alpha', 'remove', '-alpha', 'off', '/tmp/zui/in.tif', '/tmp/djpdf-ux58jik9/image.png']
DEBUG:convert-im6.q16: memory allocation failed `/tmp/zui/in.tif' @ error/tiff.c/ReadTIFFImage/1619.
convert-im6.q16: no images defined `/tmp/djpdf-ux58jik9/image.png' @ error/convert.c/ConvertImageCommand/3258.

ERROR:Command '['convert', '-colorspace', 'sRGB', '-profile', '/home/ch/.local/lib/python3.6/site-packages/djpdf/argyllcms-srgb.icm', '-background', '#ffffff', '-alpha', 'remove', '-alpha', 'off', '/tmp/zui/in.tif', '/tmp/djpdf-ux58jik9/image.png']' returned non-zero exit status 1
DEBUG:Running command: ['convert', '-colorspace', 'sRGB', '-profile', '/home/ch/.local/lib/python3.6/site-packages/djpdf/argyllcms-srgb.icm', '-background', '#ffffff', '-alpha', 'remove', '-alpha', 'off', '/tmp/zui/in.tif', '/tmp/djpdf-ux58jik9/image.png']
DEBUG:Exception occurred:
Traceback (most recent call last):
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdfcli.py", line 424, in main
    build_pdf(pages, out_file)
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 631, in build_pdf
    pages, pdf_filename, process_semaphore, progress_cb))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 614, in build_pdf_async
    for page in pages])
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 605, in progress_wrapper
    res = yield from fut
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 520, in json
    return (yield from self._cache.get(self._json(process_semaphore)))
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/util.py", line 110, in get
    self._content = yield from content_future
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 535, in _json
    get_dpi(psem))
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 387, in json
    return (yield from self._cache.get(self._json(process_semaphore)))
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/util.py", line 110, in get
    self._content = yield from content_future
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 392, in _json
    (yield from self._foreground_image.filename(psem)) is None):
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 337, in filename
    return (yield from self._cache.get(self._filename(process_semaphore)))
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/util.py", line 110, in get
    self._content = yield from content_future
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 356, in _filename
    (yield from self._input_image.filename(psem))),
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 226, in filename
    return (yield from self._cache.get(self._filename(process_semaphore)))
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/util.py", line 110, in get
    self._content = yield from content_future
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/scans2pdf.py", line 239, in _filename
    path.abspath(fname)], psem)
  File "/home/ch/.local/lib/python3.6/site-packages/djpdf/util.py", line 154, in run_command_async
    raise CalledProcessError(proc.returncode, args, None)
subprocess.CalledProcessError: Command '['convert', '-colorspace', 'sRGB', '-profile', '/home/ch/.local/lib/python3.6/site-packages/djpdf/argyllcms-srgb.icm', '-background', '#ffffff', '-alpha', 'remove', '-alpha', 'off', '/tmp/zui/in.tif', '/tmp/djpdf-ux58jik9/image.png']' returned non-zero exit status 1.

ERROR:Operation failed
```
So it says that memory allocation failed. Hm.

**Comment by Unrud** [comment]
> Then it would just require to change ``policy.xml`` accordingly.

I didn't knew that it can be configured in a file.

> So it says that memory allocation failed. Hm.

ImageMagick requires a lot of memory when converting big files.

**Comment by Unrud** [comment]
I close the issue because I can't do anything about the memory issue.

**Comment by chrisersen** [comment]
Thanks a lot. I hope that I can fix the problems and can come back again using djpdf.
