### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ovari** [Unrud/djpdf#9]
How can translations be provided to this project?

Can translations for this project be hosted on [Weblate](https://hosted.weblate.org/)?

Thank you

**Comment by Unrud** [comment]
The project is not translatable. There are currently no plans.

**Comment by Vistaus** [comment]
I support this request and will provide the Dutch translation once implemented.

**Comment by Unrud** [comment]
The Qt-GUI, Appstream metadata and Desktop file are translatable now. See [/po](https://github.com/Unrud/djpdf/tree/master/po) folder.

> Can translations for this project be hosted on [Weblate](https://hosted.weblate.org/)?

Yes, it would be possible.

**Comment by Unrud** [comment]
@ovari https://hosted.weblate.org/projects/djpdf/djpdfgui

**Comment by ovari** [comment]
Thank you @Unrud. Hungarian 100% complete. Please merge. Thank you once again.
